server:
  port: 8090

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuliugen/spring-cloud-config.git #这里类似于公用的，用于回退查找
          search-paths: configs

#使用Dalston.SR2或者Dalston.SR3会报错
encrypt:
  key-store:
    location: classpath:/server.jks
    password: letmein
    alias: mytestkey
    secret: changeme
