server:
  port: 8761

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false #eureka服务发现的话，就不需要在这里注册，不要作为Eureka Client，而是Eureka Server
    fetch-registry: false #eureka服务发现的话，就不需要在这里注册，不要作为Eureka Client，而是Eureka Server
    service-url: #将Eureka注册到指定的url
      defaultZone: http://${security.user.name}:${security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false # false关闭Eureka的保护模式，开发的时候使用
    eviction-interval-timer-in-ms: 1000 #清理间隔，默认是60*1000 毫秒
    renewal-threshold-update-interval-ms: 1000

#  dashboard:
#    enabled: true
#    path: /eureka-ui

#logging:
#  level: debug

