spring:
  application:
    name: user-server-provider
  profiles:
    active: true

server:
  port: 8085

eureka-server:
  hostname: 127.0.0.1
  port: 8761
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 1 #默认30秒，Indicates how often(in seconds) to fetch the registry information from the eureka server.
    healthcheck.enabled: true
    service-url: #Eureka服务的地址
      defaultZone: http://${eureka-server.security.user.name}:${eureka-server.security.user.password}@${eureka-server.hostname}:${eureka-server.port}/eureka/
#      defaultZone: http://${eureka-server.security.user.name}:${eureka-server.security.user.password}@${eureka-server.hostname}:${spring.cloud.client.ipAddress}:${eureka-server.port}/eureka/
  instance:
    prefer-ip-address: true #在Eureka注册管理界面上显示微服务真是的IP地址
    #instance-id: ${spring.application.name}:${server.port}  #定制Eureka注册管理界面上显示的实例名称
    status-page-url-path: ${eureka-server.hostname}:${eureka-server.port}/info
    health-check-url-path: ${eureka-server.hostname}:${eureka-server.port}/health
    lease-renewal-interval-in-seconds: 1  #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 1  #租期到期时间（默认90秒）
