spring:
  application:
    name: user-server-consumer-ribbon-without-eureka

server:
  port: 9092

eureka-server:
  hostname: 127.0.0.1
  port: 8761
  security:
    user:
      name: admin
      password: admin

eureka:
  client:
    registry-fetch-interval-seconds: 1
    service-url:
      defaultZone: http://${eureka-server.security.user.name}:${eureka-server.security.user.password}@${eureka-server.hostname}:${eureka-server.port}/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1  #租期更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 1  #租期到期时间（默认90秒）

#Ribbon不使用Eureka
ribbon:
  eureka:
   enabled: false

#Ribbon使用的user-server-provider微服务列表
user-server-provider:
  ribbon:
    listOfServers: locolhost:8085