spring:
  application:
    name: hystrix-server-turbine-use-context

server:
  port: 8062

eureka-server:
  hostname: 127.0.0.1
  port: 8761
  security:
    user:
      name: admin
      password: admin

#需要把Turbine注册到Eureka上
eureka:
  client:
    service-url: #Eureka服务的地址
      defaultZone: http://${eureka-server.security.user.name}:${eureka-server.security.user.password}@${eureka-server.hostname}:${eureka-server.port}/eureka/
  instance:
    prefer-ip-address: true #在Eureka注册管理界面上显示微服务真是的IP地址

#监控多个实例的配置,第二种方式
turbine:
  aggregator:
    clusterConfig: USER-SERVER-CONSUMER-RIBBON-WITH-HYSTRIX-USE-CONTEXT
  appConfig: user-server-consumer-ribbon-with-hystrix-use-context

#由于user-server-consumer-ribbon-with-hystrix-use-context中使用到的是加了前缀ribbon，因此在进行监控的时候都要进行相应的处理
turbine.instanceUrlSuffix.USER-SERVER-CONSUMER-RIBBON-WITH-HYSTRIX-USE-CONTEXT: /ribbon/hystrix.stream

#日志级别设置为DEBUG
logging:
  level:
    root: DEBUG

